wally output

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -26,8 +26,12 @@ jobs:
           key: aftman-${{ hashFiles('aftman.toml') }}
       - name: Install Wally dependencies
         run: wally install
-      - name: List installed Wally packages
-        run: ls -R Packages
+      - name: Show working directory
+        run: pwd
+      - name: Check Wally install output
+        run: |
+         ls -al
+         ls -al Packages || echo "Packages folder not found"
 
   luau-tests:
     name: Run Luau tests via Open Cloud
